//! Graves RNN-MDN handwriting synthesis (1308.0850), ported to pure Rust from the pretrained
//! `sjvasquez/handwriting-synthesis` weights. Forward pass only — 3 stacked LSTM-400 layers with a
//! soft attention "window" over the one-hot character sequence, and a 20-component bivariate
//! Gaussian mixture-density output head. Reads the flat f16 blob produced by `tools/convert_weights.py`
//! (layout mirrored in `load`); the NumPy twin in `tools/reference.py` validates this math.
//!
//! The model emits one continuous `(dx, dy, pen-up)` trajectory for a whole line; `compose.rs`
//! handles substitution + line wrapping, and `typeset.rs` lays the lines out on the page.

use crate::geom::Point;

/// 73-char alphabet (mirrors `drawing.alphabet` upstream and `tools/convert_weights.py`).
/// Index 0 is NUL (used as the sequence terminator). Uppercase Q/X/Z are absent — `compose.rs`
/// substitutes them before synthesis.
pub const ALPHABET: &str =
    "\u{0} !\"#'(),-.0123456789:;?ABCDEFGHIJKLMNOPRSTUVWYabcdefghijklmnopqrstuvwxyz";

/// Model output units per em. Calibrated so the model's x-height (~7 units) ≈ 0.5 em
/// (see the scale measurement in `tools/reference.py`). `font_size_mm` scales from here.
pub const UNITS_PER_EM: f32 = 14.0;

/// Hard cap on sampled timesteps (matches upstream `MAX_STROKE_LEN`).
const MAX_STROKE_LEN: usize = 1200;

// ---- sampling-quality knobs (see `generate_word`) ----
//
// The model's attention window can skate over characters it doesn't expect (rare letter sequences,
// non-English words), producing skipped or garbled letters; and per-word generation ends against
// the sequence terminator, which rushes final letters and amputates delayed strokes (t-bars and
// i-dots are written after the word body in real hands). All sampling problems, not weight
// problems, fixed here:
//  • the attention sequence carries a trailing space before NUL (as in the training data), so the
//    model finishes final letters under "a space comes next" instead of against the end;
//  • after attention reaches that space, keep sampling briefly and adopt trailing strokes that
//    read as delayed strokes (a wide high bar over the word's right region, or a mark well inside
//    it), discarding the landing tick / first letter of an imagined next word;
//  • score every attempt by its weakest character's attention dwell, and resample with a derived
//    seed when a character was skipped, keeping the best of a few attempts.
// What this cannot fix: letters the model *visits* but under-forms (a shallow y-tail reading as v,
// a final n arch reading as r) — that's the hand itself; try a different golden style for those.

/// Extra timesteps allowed after the stop condition, to pick up delayed strokes (t-bars, i-dots).
const TRAIL_MAX_STEPS: usize = 32;
/// Hard bounds for trailing ink, in model units (14/em): it may overshoot the word a little (this
/// hand's t-bars sweep well past the stem) but escaping these means the model is writing on.
const TRAIL_MARGIN_LEFT: f32 = 6.0;
const TRAIL_MARGIN_RIGHT: f32 = 12.0;
const TRAIL_MARGIN_Y: f32 = 7.0;
/// Adoption test for a completed trailing stroke, all in model units. A delayed stroke never
/// dips toward the baseline (t-bars cross at or above x-height ≈ 7, i-dots float higher), and it
/// is either a wide bar overlapping the word's right region or a mark well inside the word. The
/// stray marks to reject — the landing tick or first letter of an imagined next word — start at
/// or past the word's right edge, hug it narrowly, and usually descend.
const TRAIL_MIN_Y: f32 = 5.0;
const TRAIL_BAR_SPAN: f32 = 4.5; // a t-bar is at least this wide...
const TRAIL_BAR_OVERLAP: f32 = 2.0; // ...and starts at least this far left of the right edge
const TRAIL_DOT_OVERLAP: f32 = 4.0; // a dot/short mark must sit clearly inside the word
/// Rejection sampling: attempts per word (the first uses the caller's seed unchanged, so words
/// that pass keep their previous look) and the acceptance threshold on `rel_dwell_score`.
/// Calibrated on English + Latin words: clean renders score ≥ ~0.67, skipped/garbled letters
/// collapse below ~0.2 — 0.45 splits the clusters with margin on both sides.
const WORD_ATTEMPTS: u32 = 4;
const MIN_REL_DWELL: f32 = 0.45;

const MAGIC: &[u8; 4] = b"KGM1";

/// One synthesized line: pen-down polylines in **em units** (baseline ≈ y=0, +y up, x from 0),
/// plus the line's total advance width (em) for alignment.
pub struct LineInk {
    pub strokes: Vec<Vec<Point>>,
    pub width: f32,
}

/// The bundled **golden priming sample** (a fixed human handwriting exemplar). Every word is
/// generated by priming on this, giving an element one consistent hand. Embedded in the binary;
/// see `tools/export_golden.py` for the format.
static GOLDEN_BYTES: &[u8] = include_bytes!("golden.bin");

struct Golden {
    /// Alphabet indices of the sample's text (no terminator).
    char_idx: Vec<usize>,
    /// Flat `[dx,dy,eos,…]` pen offsets (starts with a leading `[0,0,1]` pen-down).
    offsets: Vec<f32>,
}

impl Golden {
    fn parse(bytes: &[u8]) -> Golden {
        assert!(bytes.len() >= 8 && &bytes[0..4] == b"KGG1", "bad golden.bin");
        let u32_at = |o: usize| u32::from_le_bytes(bytes[o..o + 4].try_into().unwrap()) as usize;
        let nchars = u32_at(4);
        let mut pos = 8;
        let char_idx: Vec<usize> = bytes[pos..pos + nchars].iter().map(|&b| b as usize).collect();
        pos += nchars;
        let nstrokes = u32_at(pos);
        pos += 4;
        let mut offsets = Vec::with_capacity(nstrokes * 3);
        for i in 0..nstrokes * 3 {
            let o = pos + i * 4;
            offsets.push(f32::from_le_bytes(bytes[o..o + 4].try_into().unwrap()));
        }
        Golden { char_idx, offsets }
    }
}

/// Per-timestep recurrent state. `phi` (length = char count) is exposed for the termination test.
#[derive(Clone)]
struct State {
    h1: Vec<f32>,
    c1: Vec<f32>,
    h2: Vec<f32>,
    c2: Vec<f32>,
    h3: Vec<f32>,
    c3: Vec<f32>,
    kappa: Vec<f32>,
    w: Vec<f32>,
    phi: Vec<f32>,
}

impl State {
    fn new(a: usize, h: usize, k: usize) -> Self {
        State {
            h1: vec![0.0; h],
            c1: vec![0.0; h],
            h2: vec![0.0; h],
            c2: vec![0.0; h],
            h3: vec![0.0; h],
            c3: vec![0.0; h],
            kappa: vec![0.0; k],
            w: vec![0.0; a],
            phi: Vec::new(),
        }
    }
}

pub struct Model {
    a: usize, // alphabet length (window dim)
    h: usize, // lstm hidden size
    k: usize, // attention mixture components
    m: usize, // output mixture components
    k1: Vec<f32>,
    b1: Vec<f32>,
    aw: Vec<f32>,
    ab: Vec<f32>,
    k2: Vec<f32>,
    b2: Vec<f32>,
    k3: Vec<f32>,
    b3: Vec<f32>,
    gw: Vec<f32>,
    gb: Vec<f32>,
    golden: Golden,
    /// The recurrent state after priming on `golden`, computed once at load and cloned per word.
    golden_state: State,
}

impl Model {
    /// Parse the f16 blob. Layout: `"KGM1"`, `<5×u32 LE>` = version, A, H, K, M, then f16 tensors
    /// row-major in the fixed order lstm1{kernel,bias}, attn{w,b}, lstm2{kernel,bias},
    /// lstm3{kernel,bias}, gmm{w,b}. Shapes derive from the header.
    pub fn load(bytes: &[u8]) -> Result<Model, String> {
        if bytes.len() < 24 || &bytes[0..4] != MAGIC {
            return Err("bad model blob (magic)".into());
        }
        let u32_at = |o: usize| u32::from_le_bytes(bytes[o..o + 4].try_into().unwrap()) as usize;
        let _version = u32_at(4);
        let a = u32_at(8);
        let h = u32_at(12);
        let k = u32_at(16);
        let m = u32_at(20);
        let out_units = 6 * m + 1;

        let mut pos = 24usize;
        let mut take = |n: usize| -> Result<Vec<f32>, String> {
            let end = pos + n * 2;
            if end > bytes.len() {
                return Err("model blob truncated".into());
            }
            let mut v = Vec::with_capacity(n);
            for i in 0..n {
                let off = pos + i * 2;
                let bits = u16::from_le_bytes([bytes[off], bytes[off + 1]]);
                v.push(f16_to_f32(bits));
            }
            pos = end;
            Ok(v)
        };

        let in1 = a + 3;
        let in23 = 3 + h + a;
        let mut model = Model {
            a,
            h,
            k,
            m,
            k1: take((in1 + h) * 4 * h)?,
            b1: take(4 * h)?,
            aw: take((a + 3 + h) * 3 * k)?,
            ab: take(3 * k)?,
            k2: take((in23 + h) * 4 * h)?,
            b2: take(4 * h)?,
            k3: take((in23 + h) * 4 * h)?,
            b3: take(4 * h)?,
            gw: take(h * out_units)?,
            gb: take(out_units)?,
            golden: Golden::parse(GOLDEN_BYTES),
            golden_state: State::new(a, h, k),
        };
        if pos != bytes.len() {
            return Err(format!("model blob leftover: {} of {}", pos, bytes.len()));
        }
        // Prime on the golden sample once; every word clones this state (cheap) instead of
        // re-running the ~800-step priming sequence.
        model.golden_state = model.prime_golden();
        Ok(model)
    }

    /// Teacher-force the golden sample to obtain the reusable primed state. The attention sequence
    /// is `golden_chars + ' ' + NUL`; a word's free-run later uses `golden_chars + ' ' + word + NUL`
    /// from this state (kappa sits at the golden/space boundary — `phi` over the word ≈ 0 here, so
    /// the primed state is effectively word-independent).
    fn prime_golden(&self) -> State {
        let space = ALPHABET.chars().position(|c| c == ' ').unwrap_or(1);
        let mut attn = self.golden.char_idx.clone();
        attn.push(space);
        attn.push(0);
        let mut st = State::new(self.a, self.h, self.k);
        let off = &self.golden.offsets;
        let mut i = 0;
        while i + 2 < off.len() {
            self.forward_step(&[off[i], off[i + 1], off[i + 2]], &mut st, &attn);
            i += 3;
        }
        st
    }

    fn out_units(&self) -> usize {
        6 * self.m + 1
    }

    /// One LSTM cell step (TF `LSTMCell` semantics: gate order i,j,f,o; forget_bias = 1.0; no
    /// peepholes/projection). `input` is the layer input; the kernel's first `input.len()` rows
    /// apply to it and the next `h` rows to `h_prev`.
    fn lstm(&self, kernel: &[f32], bias: &[f32], input: &[f32], h_prev: &[f32], c_prev: &[f32]) -> (Vec<f32>, Vec<f32>) {
        let hsz = self.h;
        let cols = 4 * hsz;
        let mut z = bias.to_vec();
        for (r, &xr) in input.iter().enumerate() {
            if xr == 0.0 {
                continue;
            }
            let base = r * cols;
            for c in 0..cols {
                z[c] += xr * kernel[base + c];
            }
        }
        let off = input.len();
        for r in 0..hsz {
            let xr = h_prev[r];
            if xr == 0.0 {
                continue;
            }
            let base = (off + r) * cols;
            for c in 0..cols {
                z[c] += xr * kernel[base + c];
            }
        }
        let mut hn = vec![0.0f32; hsz];
        let mut cn = vec![0.0f32; hsz];
        for i in 0..hsz {
            let ig = sigmoid(z[i]);
            let jg = z[hsz + i].tanh();
            let fg = sigmoid(z[2 * hsz + i] + 1.0); // forget_bias = 1.0
            let og = sigmoid(z[3 * hsz + i]);
            let cc = fg * c_prev[i] + ig * jg;
            cn[i] = cc;
            hn[i] = og * cc.tanh();
        }
        (hn, cn)
    }

    /// One full timestep. `idx` is the character-index sequence (incl. trailing NUL). Returns the
    /// raw `6M+1` MDN parameter vector (pre-parse) and updates `st`. This is what the gold test pins.
    fn forward_step(&self, x: &[f32], st: &mut State, idx: &[usize]) -> Vec<f32> {
        let (a, h, k) = (self.a, self.h, self.k);

        // LSTM 1: input = [w_prev, x]
        let mut in1 = Vec::with_capacity(a + 3);
        in1.extend_from_slice(&st.w);
        in1.extend_from_slice(x);
        let (h1, c1) = self.lstm(&self.k1, &self.b1, &in1, &st.h1, &st.c1);

        // Attention: params from [w_prev, x, h1]
        let mut ain = Vec::with_capacity(a + 3 + h);
        ain.extend_from_slice(&st.w);
        ain.extend_from_slice(x);
        ain.extend_from_slice(&h1);
        let mut ap = self.ab.clone();
        dense_into(&ain, &self.aw, 3 * k, &mut ap);
        for v in ap.iter_mut() {
            *v = softplus(*v);
        }
        // phi[u] = Σ_k α_k exp(-(κ_k - u)² / β_k); κ cumulative, β ≥ .01
        let u = idx.len();
        let mut phi = vec![0.0f32; u];
        for kk in 0..k {
            let alpha = ap[kk];
            let beta = ap[k + kk].max(0.01);
            let kappa = st.kappa[kk] + ap[2 * k + kk] / 25.0;
            st.kappa[kk] = kappa;
            for uu in 0..u {
                let d = kappa - uu as f32;
                phi[uu] += alpha * (-(d * d) / beta).exp();
            }
        }
        // w = Σ_u phi[u] · onehot(idx[u])  (onehot is sparse → scatter-add)
        let mut w = vec![0.0f32; a];
        for uu in 0..u {
            w[idx[uu]] += phi[uu];
        }

        // LSTM 2: [x, h1, w]   LSTM 3: [x, h2, w]
        let mut in2 = Vec::with_capacity(3 + h + a);
        in2.extend_from_slice(x);
        in2.extend_from_slice(&h1);
        in2.extend_from_slice(&w);
        let (h2, c2) = self.lstm(&self.k2, &self.b2, &in2, &st.h2, &st.c2);

        let mut in3 = Vec::with_capacity(3 + h + a);
        in3.extend_from_slice(x);
        in3.extend_from_slice(&h2);
        in3.extend_from_slice(&w);
        let (h3, c3) = self.lstm(&self.k3, &self.b3, &in3, &st.h3, &st.c3);

        // MDN head reads h3 only
        let mut gmm = self.gb.clone();
        dense_into(&h3, &self.gw, self.out_units(), &mut gmm);

        st.h1 = h1;
        st.c1 = c1;
        st.h2 = h2;
        st.c2 = c2;
        st.h3 = h3;
        st.c3 = c3;
        st.w = w;
        st.phi = phi;
        gmm
    }

    /// Sample one `(dx, dy, pen-up)` offset from a raw MDN parameter vector under `bias`.
    /// PRNG draw order: mixture component, then the two normals, then the pen-up coin.
    fn sample(&self, gmm: &[f32], bias: f32, rng: &mut Mulberry32) -> (f32, f32, bool) {
        let m = self.m;
        let mut pis = vec![0.0f32; m];
        for i in 0..m {
            pis[i] = gmm[i] * (1.0 + bias); // softmax(π·(1+bias))
        }
        softmax(&mut pis);

        let uc = rng.next_f32();
        let mut acc = 0.0;
        let mut sel = m - 1;
        for i in 0..m {
            acc += pis[i];
            if uc <= acc {
                sel = i;
                break;
            }
        }
        let (z1, z2) = rng.normal2();
        let s1 = ((gmm[m + sel] - bias).exp()).max(1e-4); // σ·exp(−bias)
        let s2 = ((gmm[2 * m + sel] - bias).exp()).max(1e-4);
        let rho = gmm[3 * m + sel].tanh().clamp(-0.9999, 0.9999);
        let dx = gmm[4 * m + sel] + s1 * z1;
        let dy = gmm[5 * m + sel] + s2 * (rho * z1 + (1.0 - rho * rho).sqrt() * z2);
        let eos = rng.next_f32() < sigmoid(gmm[6 * m]);
        (dx, dy, eos)
    }

    /// MDN parameter vector for a hidden state's `h3` (the network's output head).
    fn mdn(&self, h3: &[f32]) -> Vec<f32> {
        let mut gmm = self.gb.clone();
        dense_into(h3, &self.gw, self.out_units(), &mut gmm);
        gmm
    }

    /// Synthesize one **word**, primed on the golden sample for a consistent hand. Returns ink in em
    /// (baseline≈0, +y up, x from 0) plus its width (em). `word` must be in-alphabet and contain no
    /// spaces (the worker splits + lays out). Deterministic for `(word, seed, bias)`: rejection
    /// sampling derives attempt seeds from `seed`, and attempt 0 IS `seed` — so words the scorer
    /// accepts first try render exactly as a single-attempt sampler would.
    pub fn generate_word(&self, word: &str, seed: u32, bias: f32) -> LineInk {
        let word_idx = encode_indices(word); // word + NUL terminator
        if word_idx.len() <= 1 {
            return LineInk { strokes: Vec::new(), width: 0.0 };
        }
        let (full_idx, word_start) = self.word_attention(&word_idx);
        let word_chars = word_idx.len() - 1;

        let mut best: Option<(f32, Vec<(f32, f32, bool)>)> = None;
        for attempt in 0..WORD_ATTEMPTS {
            let aseed = seed.wrapping_add(attempt.wrapping_mul(0x85EB_CA6B));
            let raw = self.sample_word(&full_idx, word_start, word_chars, aseed, bias);
            let score = rel_dwell_score(&raw.dwell).min(width_score(&raw.traj, word_chars));
            if score >= MIN_REL_DWELL {
                return finish_word(&raw.traj);
            }
            if best.as_ref().map_or(true, |(s, _)| score > *s) {
                best = Some((score, raw.traj));
            }
        }
        finish_word(&best.expect("WORD_ATTEMPTS > 0").1)
    }

    /// The attention sequence for one word — golden text + space + word + **space** + NUL — and
    /// the index of the word's first char within it. The free-run starts from the cached
    /// golden-primed state (kappa at the golden/space boundary) and advances through the word.
    /// The trailing space is load-bearing: in the training data a word is always followed by one,
    /// so the model finishes final letters (last arches, descender tails) under "a space comes
    /// next" instead of rushing them against the end of the sequence. `word_idx` is
    /// `encode_indices` output (chars + NUL).
    fn word_attention(&self, word_idx: &[usize]) -> (Vec<usize>, usize) {
        let space = ALPHABET.chars().position(|c| c == ' ').unwrap_or(1);
        let mut full_idx = self.golden.char_idx.clone();
        full_idx.push(space);
        full_idx.extend_from_slice(&word_idx[..word_idx.len() - 1]); // the word's chars
        full_idx.push(space);
        full_idx.push(0); // NUL terminator
        let word_start = full_idx.len() - 1 - word_idx.len();
        (full_idx, word_start)
    }

    /// One free-run attempt: sample the trajectory, accumulate per-character attention dwell, and
    /// terminate carefully. The stop condition (attention argmax on the NUL terminator + pen up)
    /// fires at the pen-lift *before* any delayed stroke — a t-bar or i-dot is written after the
    /// word body — so after it fires we keep sampling for a short trail window and extend the cut
    /// over any stroke that completes inside the word's ink box, discarding ink that wanders off
    /// (the start of an imagined next word).
    fn sample_word(&self, full_idx: &[usize], word_start: usize, word_chars: usize, seed: u32, bias: f32) -> Sampled {
        let mut st = self.golden_state.clone();
        let mut rng = Mulberry32::new(seed.wrapping_mul(0x9E37_79B1).wrapping_add(0x6D2B_79F5));
        let mut gmm = self.mdn(&st.h3); // first offset comes from the primed state
        let mut x = self.sample(&gmm, bias, &mut rng);

        let max_steps = (40 * word_chars).clamp(1, MAX_STROKE_LEN);
        let mut cx = 0.0f32;
        let mut cy = 0.0f32;
        let mut traj: Vec<(f32, f32, bool)> = Vec::new();
        let mut dwell = vec![0.0f32; word_chars];
        // Set once the stop condition fires: accepted end of the word + its ink box.
        let mut cut: Option<(usize, [f32; 4])> = None; // (traj len, [min_x, max_x, min_y, max_y])
        let mut trail = 0usize;

        while traj.len() < max_steps + TRAIL_MAX_STEPS {
            cx += x.0;
            cy += x.1;
            traj.push((cx, cy, x.2));

            // Done once attention reaches the trailing space (index len-2) — the word's letters
            // are behind the window and the model is in the inter-word gap. (The first iteration
            // sees the golden state's shorter `phi`, whose argmax is well before the word's end —
            // safe for the stop test, and skipped by the dwell guard.)
            let attn_done = argmax(&st.phi) >= full_idx.len() - 2;
            match &mut cut {
                None => {
                    if attn_done && x.2 {
                        cut = Some((traj.len(), ink_box(&traj)));
                    } else if traj.len() >= max_steps {
                        break; // never terminated: cap as before
                    }
                }
                Some((end, bx)) => {
                    trail += 1;
                    let inside = cx >= bx[0] - TRAIL_MARGIN_LEFT
                        && cx <= bx[1] + TRAIL_MARGIN_RIGHT
                        && cy >= bx[2] - TRAIL_MARGIN_Y
                        && cy <= bx[3] + TRAIL_MARGIN_Y;
                    if !inside {
                        break; // escaped the word's vicinity — discard everything past `end`
                    }
                    if x.2 {
                        // Stroke completed: adopt it only if it looks like a delayed stroke —
                        // high-riding, and either a wide bar over the word's right region (the
                        // terminal t-bar) or a mark well inside the word (an i-dot). Anything
                        // else is the model starting an imagined next word.
                        let s = ink_box(&traj[*end..]);
                        let bar = s[1] - s[0] >= TRAIL_BAR_SPAN && s[0] <= bx[1] - TRAIL_BAR_OVERLAP;
                        let dot = s[0] <= bx[1] - TRAIL_DOT_OVERLAP;
                        if s[2] < TRAIL_MIN_Y || !(bar || dot) {
                            break;
                        }
                        *end = traj.len();
                    }
                    if trail >= TRAIL_MAX_STEPS {
                        break;
                    }
                }
            }

            gmm = self.forward_step(&[x.0, x.1, if x.2 { 1.0 } else { 0.0 }], &mut st, &full_idx);
            x = self.sample(&gmm, bias, &mut rng);
            // Attention dwell per word character: how much window mass each received in total. A
            // skipped/garbled letter shows up as a near-zero slot (see `rel_dwell_score`).
            if st.phi.len() == full_idx.len() {
                for (i, d) in dwell.iter_mut().enumerate() {
                    *d += st.phi[word_start + i];
                }
            }
        }

        if let Some((end, _)) = cut {
            traj.truncate(end);
        }
        Sampled { traj, dwell }
    }
}

/// One sampling attempt's raw output: the trajectory and per-word-char attention dwell.
struct Sampled {
    traj: Vec<(f32, f32, bool)>,
    dwell: Vec<f32>,
}

/// Bounding box of a trajectory's points as `[min_x, max_x, min_y, max_y]` (model units).
fn ink_box(traj: &[(f32, f32, bool)]) -> [f32; 4] {
    let mut b = [f32::INFINITY, f32::NEG_INFINITY, f32::INFINITY, f32::NEG_INFINITY];
    for &(x, y, _) in traj {
        b[0] = b[0].min(x);
        b[1] = b[1].max(x);
        b[2] = b[2].min(y);
        b[3] = b[3].max(y);
    }
    b
}

/// Attention-dwell quality score: the weakest character's dwell relative to the word's median.
/// A cleanly-written word scores near 1; a skipped letter drives it toward 0. Relative, so it
/// self-calibrates across word lengths, biases, and styles.
fn rel_dwell_score(dwell: &[f32]) -> f32 {
    if dwell.is_empty() {
        return 1.0;
    }
    let mut sorted = dwell.to_vec();
    sorted.sort_by(|a, b| a.total_cmp(b));
    let median = sorted[sorted.len() / 2].max(1e-6);
    sorted[0] / median
}

/// Coarse width sanity: a word whose ink is drastically narrower than ~0.15 em per character has
/// dropped letters even if the window nominally visited them. Returns a score on the same scale
/// as `rel_dwell_score` (>= threshold passes).
fn width_score(traj: &[(f32, f32, bool)], word_chars: usize) -> f32 {
    if traj.is_empty() {
        return 0.0;
    }
    let b = ink_box(traj);
    let width_em = (b[1] - b[0]) / UNITS_PER_EM;
    if width_em >= 0.15 * word_chars as f32 { 1.0 } else { 0.0 }
}

// ---- post-processing: scale to em, split into strokes ----

/// Convert absolute model coords into em-space pen-down polylines (baseline≈0, x from 0), removing
/// global slant/offset (least-squares y = a + b·x), and report width (em). The model's y is **+up**
/// (ascenders positive), the same convention `typeset` expects — it applies the page (+y down) flip.
fn finish_word(raw: &[(f32, f32, bool)]) -> LineInk {
    if raw.is_empty() {
        return LineInk { strokes: Vec::new(), width: 0.0 };
    }
    // No deslant: words are short (a slope fit would be noisy and tilt them inconsistently), and
    // golden priming keeps their baseline consistent. Just scale to em and shift x so the word
    // starts at 0. Model y is +up (= em convention); `place_word` applies the page flip.
    let mut min_x = f32::INFINITY;
    for &(x, _, _) in raw {
        min_x = min_x.min(x);
    }

    let mut strokes: Vec<Vec<Point>> = Vec::new();
    let mut cur: Vec<Point> = Vec::new();
    let mut max_em_x = 0.0f32;
    for &(x, y, eos) in raw {
        let em_x = (x - min_x) / UNITS_PER_EM;
        max_em_x = max_em_x.max(em_x);
        cur.push(Point { x: em_x, y: y / UNITS_PER_EM, pressure: 1.0 });
        if eos {
            if cur.len() >= 2 {
                strokes.push(std::mem::take(&mut cur));
            } else {
                cur.clear();
            }
        }
    }
    if cur.len() >= 2 {
        strokes.push(cur);
    }
    LineInk { strokes, width: max_em_x }
}

/// Map text to alphabet indices, plus the trailing NUL terminator the attention window stops on.
/// Unknown chars (should not occur after substitution) fall back to space.
fn encode_indices(text: &str) -> Vec<usize> {
    let space = ALPHABET.chars().position(|c| c == ' ').unwrap_or(1);
    let mut out: Vec<usize> = text
        .chars()
        .map(|c| ALPHABET.chars().position(|a| a == c).unwrap_or(space))
        .collect();
    out.push(0); // NUL terminator
    out
}

// ---- small math helpers ----

#[inline]
fn sigmoid(x: f32) -> f32 {
    1.0 / (1.0 + (-x).exp())
}

#[inline]
fn softplus(x: f32) -> f32 {
    // numerically stable: log1p(exp(-|x|)) + max(x,0)
    (-x.abs()).exp().ln_1p() + x.max(0.0)
}

fn softmax(v: &mut [f32]) {
    let mx = v.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0;
    for x in v.iter_mut() {
        *x = (*x - mx).exp();
        sum += *x;
    }
    for x in v.iter_mut() {
        *x /= sum;
    }
}

fn argmax(v: &[f32]) -> usize {
    let mut best = 0;
    let mut bv = f32::NEG_INFINITY;
    for (i, &x) in v.iter().enumerate() {
        if x > bv {
            bv = x;
            best = i;
        }
    }
    best
}

/// `out[c] += Σ_r input[r] · w[r·cols + c]`. `out` is pre-seeded with the bias by the caller.
fn dense_into(input: &[f32], w: &[f32], cols: usize, out: &mut [f32]) {
    for (r, &xr) in input.iter().enumerate() {
        if xr == 0.0 {
            continue;
        }
        let base = r * cols;
        for c in 0..cols {
            out[c] += xr * w[base + c];
        }
    }
}

/// IEEE half → f32.
fn f16_to_f32(bits: u16) -> f32 {
    let sign = (bits >> 15) & 1;
    let exp = (bits >> 10) & 0x1f;
    let mant = bits & 0x3ff;
    let val = if exp == 0 {
        if mant == 0 {
            0.0
        } else {
            (mant as f32) * 2f32.powi(-24) // subnormal
        }
    } else if exp == 0x1f {
        if mant == 0 {
            f32::INFINITY
        } else {
            f32::NAN
        }
    } else {
        (1.0 + (mant as f32) / 1024.0) * 2f32.powi(exp as i32 - 15)
    };
    if sign == 1 {
        -val
    } else {
        val
    }
}

/// Deterministic PRNG (mulberry32) — keeps `(text, seed, bias)` reproducible so JS-side
/// memoization stays valid.
struct Mulberry32 {
    state: u32,
}

impl Mulberry32 {
    fn new(seed: u32) -> Self {
        Mulberry32 { state: seed }
    }
    fn next_f32(&mut self) -> f32 {
        self.state = self.state.wrapping_add(0x6d2b_79f5);
        let a = self.state;
        let mut t = (a ^ (a >> 15)).wrapping_mul(1 | a);
        t = (t.wrapping_add((t ^ (t >> 7)).wrapping_mul(61 | t))) ^ t;
        ((t ^ (t >> 14)) as f32) / 4_294_967_296.0
    }
    /// Two independent standard normals (Box–Muller).
    fn normal2(&mut self) -> (f32, f32) {
        let u1 = self.next_f32().max(1e-7);
        let u2 = self.next_f32();
        let r = (-2.0 * u1.ln()).sqrt();
        let ang = std::f32::consts::TAU * u2;
        (r * ang.cos(), r * ang.sin())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Gold test: feed the exact teacher-forced inputs from `tools/reference.py fixtures` and
    /// assert the Rust forward pass reproduces the NumPy reference's raw MDN params + window.
    #[test]
    fn matches_reference_traces() {
        let blob = std::fs::read("../public/models/kg_model.f16.bin")
            .expect("run tools/convert_weights.py first");
        let model = Model::load(&blob).expect("load model");
        let fixtures: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string("tests/fixtures.json").unwrap()).unwrap();

        let idx: Vec<usize> = fixtures["char_indices"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        let inputs = fixtures["inputs"].as_array().unwrap();
        let steps = fixtures["steps"].as_array().unwrap();

        let mut st = State::new(model.a, model.h, model.k);
        for (s, inp) in steps.iter().zip(inputs) {
            let x: Vec<f32> = inp.as_array().unwrap().iter().map(|v| v.as_f64().unwrap() as f32).collect();
            let gmm = model.forward_step(&x, &mut st, &idx);

            let ref_gmm: Vec<f32> = s["gmm"].as_array().unwrap().iter().map(|v| v.as_f64().unwrap() as f32).collect();
            let max_d = gmm.iter().zip(&ref_gmm).map(|(a, b)| (a - b).abs()).fold(0.0f32, f32::max);
            assert!(max_d < 2e-2, "gmm mismatch, max |Δ| = {max_d}");

            let ref_w: Vec<f32> = s["w"].as_array().unwrap().iter().map(|v| v.as_f64().unwrap() as f32).collect();
            let wd = st.w.iter().zip(&ref_w).map(|(a, b)| (a - b).abs()).fold(0.0f32, f32::max);
            assert!(wd < 1e-3, "window mismatch, max |Δ| = {wd}");
        }
    }

    /// Dev diagnostic (ignored by default): prints attempt-0 dwell scores for a spread of easy and
    /// attention-hostile words and dumps an SVG grid of the final (rejection-sampled) ink to
    /// /tmp/kg_dwell_diag.svg for eyeballing. Use it to recalibrate MIN_REL_DWELL / the trail
    /// constants after any change to sampling, the golden style, or the weights.
    /// Run: cargo test diag_dwell -- --ignored --nocapture
    #[test]
    #[ignore]
    fn diag_dwell() {
        let blob = std::fs::read("../public/models/kg_model.f16.bin").expect("blob");
        let model = Model::load(&blob).unwrap();
        let words = [
            "hello", "world", "running", "the", "through", // English (in-distribution)
            "consectetur", "lobortis", "porttitor", "adipiscing", "vulputate", // Latin (OOD)
            "dolor", "odio", "sit", "ut", "et", "ante", "amet", // short + t-final
            "my", "name", "man", "brothers", "children", // weak-ending suspects
        ];
        let bias = 1.8f32;
        let mut svg = String::from("<svg xmlns='http://www.w3.org/2000/svg' width='1400' height='2600' style='background:#fff'>\n");
        let em = 22.0f32;
        for (wi, word) in words.iter().enumerate() {
            for seed in 1u32..=4 {
                let word_idx = encode_indices(word);
                let (full_idx, word_start) = model.word_attention(&word_idx);
                let s = model.sample_word(&full_idx, word_start, word_idx.len() - 1, seed, bias);
                let score = rel_dwell_score(&s.dwell).min(width_score(&s.traj, word_idx.len() - 1));
                let dw: Vec<String> = s.dwell.iter().map(|d| format!("{d:.1}")).collect();
                println!("{word:>12} seed {seed}: score {score:.3}  dwell [{}]", dw.join(" "));

                // Render the FINAL (rejection-sampled) ink for the eyeball grid.
                let ink = model.generate_word(word, seed, bias);
                let ox = 40.0 + (seed - 1) as f32 * 340.0;
                let oy = 60.0 + wi as f32 * 110.0;
                for stroke in &ink.strokes {
                    let d: Vec<String> = stroke
                        .iter()
                        .enumerate()
                        .map(|(i, p)| format!("{}{:.1},{:.1}", if i == 0 { "M" } else { "L" }, ox + p.x * em, oy - p.y * em))
                        .collect();
                    svg.push_str(&format!("<path d='{}' fill='none' stroke='#111' stroke-width='1.3'/>\n", d.join(" ")));
                }
            }
        }
        svg.push_str("</svg>\n");
        std::fs::write("/tmp/kg_dwell_diag.svg", svg).unwrap();
        println!("wrote /tmp/kg_dwell_diag.svg");
    }

    #[test]
    fn synthesizes_plausible_strokes() {
        let blob = std::fs::read("../public/models/kg_model.f16.bin").expect("blob");
        let model = Model::load(&blob).unwrap();
        let ink = model.generate_word("hello", 7, 2.5);
        assert!(!ink.strokes.is_empty(), "no strokes");
        assert!(ink.width > 1.0, "implausible width {}", ink.width);
        let pts: usize = ink.strokes.iter().map(|s| s.len()).sum();
        assert!(pts > 20, "too few points {pts}");
    }

    #[test]
    fn generation_is_deterministic() {
        let blob = std::fs::read("../public/models/kg_model.f16.bin").expect("blob");
        let model = Model::load(&blob).unwrap();
        let a = model.generate_word("consectetur", 5, 1.8);
        let b = model.generate_word("consectetur", 5, 1.8);
        assert_eq!(a.width, b.width);
        assert_eq!(a.strokes.len(), b.strokes.len());
        for (sa, sb) in a.strokes.iter().zip(&b.strokes) {
            assert_eq!(sa.len(), sb.len());
            for (pa, pb) in sa.iter().zip(sb) {
                assert_eq!((pa.x, pa.y), (pb.x, pb.y));
            }
        }
    }

    #[test]
    fn rel_dwell_score_flags_skipped_chars() {
        // Even dwell → near 1; one starved slot → collapses toward 0; degenerate → trivially 1.
        assert!((rel_dwell_score(&[20.0, 22.0, 18.0]) - 18.0 / 20.0).abs() < 1e-6);
        assert!(rel_dwell_score(&[20.0, 22.0, 0.5]) < 0.05);
        assert_eq!(rel_dwell_score(&[7.0]), 1.0);
        assert_eq!(rel_dwell_score(&[]), 1.0);
    }

    /// Pins the rejection-sampling mechanism to a known-bad fixture: `dolor` at seed 4 garbles on
    /// attempt 0 (attention skips the tail — dwell collapses), so `generate_word` must reject it
    /// and return a different, accepted attempt. If a recalibration makes attempt 0 pass, update
    /// the fixture to a currently-failing (word, seed).
    #[test]
    fn rejection_sampling_replaces_garbled_attempts() {
        let blob = std::fs::read("../public/models/kg_model.f16.bin").expect("blob");
        let model = Model::load(&blob).unwrap();
        let word = "dolor";
        let (seed, bias) = (4u32, 1.8f32);

        let word_idx = encode_indices(word);
        let (full_idx, word_start) = model.word_attention(&word_idx);
        let a0 = model.sample_word(&full_idx, word_start, word_idx.len() - 1, seed, bias);
        let a0_score = rel_dwell_score(&a0.dwell).min(width_score(&a0.traj, word_idx.len() - 1));
        assert!(a0_score < MIN_REL_DWELL, "fixture stale: attempt 0 now passes ({a0_score:.3})");

        let chosen = model.generate_word(word, seed, bias);
        let rejected = finish_word(&a0.traj);
        assert!(
            chosen.width != rejected.width || chosen.strokes.len() != rejected.strokes.len(),
            "generate_word returned the garbled attempt"
        );
    }
}
