#!/usr/bin/env python3
"""Export one upstream handwriting-style example as the bundled **golden priming sample**.

Every handwriting word is generated by priming the model on this single fixed sample (Graves'
priming), which is what makes an element's words share one consistent hand. The primed state is
computed once at load and reused for every word (see crate/src/model.rs), so the sample's length
is free at runtime.

Run (one-off, dev-time):

    uv run --python 3.11 --with numpy python tools/export_golden.py /path/to/style-9

…where the prefix points at `style-9-strokes.npy` / `style-9-chars.npy` from
sjvasquez/handwriting-synthesis. Output: crate/src/golden.bin (committed, ~9 KB).

Format (little-endian), mirrored by `Golden::parse` in model.rs:
    "KGG1", u32 nchars, nchars × u8 (alphabet indices), u32 nstrokes, nstrokes × 3 × f32 (dx,dy,eos)
"""
import struct
import sys
from pathlib import Path

import numpy as np

# Mirrors model.rs ALPHABET / drawing.alphabet. Index 0 = NUL.
ALPHABET = (
    "\x00 !\"#'(),-.0123456789:;?"
    "ABCDEFGHIJKLMNOPRSTUVWYabcdefghijklmnopqrstuvwxyz"
)
IDX = {c: i for i, c in enumerate(ALPHABET)}
SPACE = IDX[" "]


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: export_golden.py <style-prefix>  (e.g. /tmp/hws/styles/style-9)")
    prefix = sys.argv[1]
    strokes = np.load(f"{prefix}-strokes.npy").astype(np.float32)  # [T,3] (dx,dy,eos)
    chars = np.load(f"{prefix}-chars.npy").tobytes().decode("utf-8", "ignore")
    idx = [IDX.get(c, SPACE) for c in chars]

    out = Path(__file__).resolve().parent.parent / "crate" / "src" / "golden.bin"
    blob = b"KGG1"
    blob += struct.pack("<I", len(idx)) + bytes(idx)
    blob += struct.pack("<I", strokes.shape[0])
    blob += np.ascontiguousarray(strokes, dtype="<f4").tobytes()
    out.write_bytes(blob)
    print(f"golden chars={chars!r} ({len(idx)} chars), {strokes.shape[0]} strokes")
    print(f"wrote {out}  ({len(blob)} bytes)")


if __name__ == "__main__":
    main()
